Federated documentation starter
ontoportal/documentation pull request #53
Opened 2024-06-04 11:37 UTC by galviset

This pull request contains all changes needed to start the federated documentation, from the Jekyll configuration to the content of the documentation itself. The shared content is based on EcoPortal's draft documentation which has been slightly edited to be generic enough for most portals.
While most of the shared content is there, the user documentation for each portal needs to be done (either by reusing the available shared content, either by adding their own specific bits of documentation).

2024-06-07 15:18 UTC, Bilelkihal commented on docs/users-guide-docs/documentation/earthportal/about.md
> +{% include documentation_nav.html %}
For the nav, when you do the include you need to explicitly specify the portal (this is why it's not getting colored when you select it),
The config you added do the job only for the paths where we have the shared doc, but for the nav you can't do the same thing

2024-06-10 11:43 UTC, Bilelkihal commented
@galviset 
The issue of the last week was not related to using the same page title, it was caused by the includes of the variables not working properly. In fact the config that you did add the values just in the scope of the specific docs, but in our case we need to use the variables in the shared documentation instead and since we have only one shared documentation then we can't really use this solution and we can't run away from passing the variables in each include

2024-06-10 14:26 UTC, galviset commented
@Bilelkihal
This is weird. I tried to rollback to the include system of variables (so passing variables in each include and change page. by include. in shared documentation), and I still witness the same issue.
The scope-specific variables were working correctly when I tested them, but it required to change `include.variable` by ` page.variable` in shared docs. Included files still have access to page variables.

2024-06-10 16:28 UTC, Bilelkihal commented
No it works perfectly when u add the includes.
you can see also for you that ontoportal and ecoportal has the same page title for home page and it's working.

in this video I just added the includes and now it's working
https://github.com/ontoportal/documentation/assets/61744974/587e1785-1cd2-4dc4-a4e0-66bf0d3f2cf0

2024-06-26 14:22 UTC, galviset commented
@Bilelkihal That pull request now contains only the documentation content for review.

2024-06-26 19:14 UTC, syphax-bouazzouni requested changes
Hard to review a 175 files change PR, can you divide it 10 small PRs (max 20 files), if you need help on that, we can arrange a meeting.

2024-06-27 09:48 UTC, galviset commented
Done, here is the entire content divided:
#55
#56
#57
#58
#59
#60
#61
#62

2024-08-02 14:07 UTC, closed without merging